[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "jupyfuncs/_version.py"
local_scheme = "no-local-version"