[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "jupyfuncs/_version.py"
tag_regex = "^v?(\\d+\\.\\d+\\.\\d+)$"