[build-system]
requires = ["setuptools>=40.8.0", "wheel", "versioneer"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "jupyfuncs/_version.py"
versionfile_build = "jupyfuncs/_version.py"
tag_prefix = ""
parentdir_prefix = "jupyfuncs-"