name: Build and Publish to PyPI

on:
  push:
    # branches:
    #   - master # 确保这匹配你的主分支名
    tags:
      - '*'  # 监听所有标签推送

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 确保能够获取全部历史和标签

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install build  # 确保在构建前安装 build 模块

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      
      - name: Check if it's a tag push and Extract tag name
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
            echo "Extracted TAG_NAME: $TAG_NAME"
          else
            echo "Not a tag push, skipping..."
          fi
  
      - name: Create GitHub Release
        if: env.TAG_NAME != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: "Description of the release"
          draft: false
          prerelease: false